-- V76: Add outbox table for integration event publishing.

CREATE TABLE IF NOT EXISTS outbox_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id             CHAR(36)     NOT NULL,
    event_type           VARCHAR(120) NOT NULL,
    event_version        INT          NOT NULL,
    aggregate_type       VARCHAR(120) NOT NULL,
    aggregate_id         VARCHAR(120) NOT NULL,
    topic                VARCHAR(255) NOT NULL,
    message_key          VARCHAR(255) NOT NULL,
    payload_json         CLOB         NOT NULL,
    status               VARCHAR(20)  NOT NULL,
    attempt_count        INT          NOT NULL DEFAULT 0,
    last_error           CLOB         NULL,
    next_attempt_at      TIMESTAMP    NULL,
    published_at         TIMESTAMP    NULL,
    version              INT          NOT NULL DEFAULT 0,
    created_by_user_id   BIGINT       NULL,
    created_date         TIMESTAMP    NULL,
    updated_by_user_id   BIGINT       NULL,
    updated_date         TIMESTAMP    NULL,
    CONSTRAINT uk_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_outbox_events_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_outbox_events_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_outbox_status_next_attempt
    ON outbox_events (status, next_attempt_at);

CREATE INDEX IF NOT EXISTS idx_outbox_topic_status
    ON outbox_events (topic, status);

CREATE INDEX IF NOT EXISTS idx_outbox_aggregate
    ON outbox_events (aggregate_type, aggregate_id);
