-- DEV SEEDER INDEX
-- Lokasi legacy: docs/database/dev-seeder.sql
--
-- File monolitik lama telah dipecah menjadi file-file seed terurut di:
--   docs/database/dev-seeder/
--
-- Tujuan:
--   - memudahkan maintenance per modul
--   - menjaga dependency data tetap eksplisit lewat penomoran file
--   - memungkinkan accounting foundation berkembang tanpa membebani seed modul lain
--
-- Jalankan setelah semua Flyway migration selesai.
-- Password user dev tetap: admin123
--
-- ============================================================
-- EXECUTION ORDER
-- ============================================================
-- Jalankan file-file berikut berurutan sesuai nama:
--
--   D001__cleanup_core.sql
--   D010__security_roles.sql
--   D020__parties.sql
--   D030__users.sql
--   D040__user_profiles.sql
--   D100__inventory_facilities.sql
--   D110__inventory_grids.sql
--   D120__inventory_containers.sql
--   D130__inventory_product_categories.sql
--   D140__inventory_brands.sql
--   D150__inventory_products.sql
--   D200__accounting_fiscal_years_and_periods.sql
--   D210__accounting_coa.sql
--   D220__accounting_schema.sql
--
-- ============================================================
-- FILE RESPONSIBILITIES
-- ============================================================
-- D001 : cleanup data dev lama (security links, parties, inventory demo, approval/news)
-- D010 : security roles dev + role permissions
-- D020 : party role type APPROVER + seed parties, addresses, contacts, identifications
-- D030 : seed users dev
-- D040 : seed user profiles dev
-- D100 : facilities
-- D110 : grids
-- D120 : containers
-- D130 : product categories
-- D140 : brands
-- D150 : products
-- D200 : fiscal years FY-2024/FY-2025 + 24 accounting periods
-- D210 : chart of accounts (3-level hierarchy, richer dev setup)
-- D220 : accounting schema mappings for all current SchemaEventType values
--
-- ============================================================
-- EXAMPLE EXECUTION (DOCKER)
-- ============================================================
-- Jalankan satu per satu:
--
--   docker exec -i mariadb-local mariadb -uroot -proot erp-test < docs/database/dev-seeder/D001__cleanup_core.sql
--   docker exec -i mariadb-local mariadb -uroot -proot erp-test < docs/database/dev-seeder/D010__security_roles.sql
--   ...
--   docker exec -i mariadb-local mariadb -uroot -proot erp-test < docs/database/dev-seeder/D220__accounting_schema.sql
--
-- ============================================================
-- EXAMPLE EXECUTION (LOCAL MARIADB)
-- ============================================================
--   mariadb -h localhost -P 3307 -uroot -proot erp-test < docs/database/dev-seeder/D001__cleanup_core.sql
--   mariadb -h localhost -P 3307 -uroot -proot erp-test < docs/database/dev-seeder/D010__security_roles.sql
--   ...
--   mariadb -h localhost -P 3307 -uroot -proot erp-test < docs/database/dev-seeder/D220__accounting_schema.sql
--
-- Catatan:
-- - File ini sekarang hanya berfungsi sebagai indeks/panduan.
-- - Tidak ada SQL orchestrator atau SOURCE chaining; dependency dijaga oleh urutan nama file.
